### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Mrgoldilocks** [z1g-project/Terbium#3]
It gave me a "failed to fetch" error message.

The one linked here (AKA the "https://terbium-46q.pages.dev/" link

on school Chromebook, but that shouldn't affect it (if I'm correct)

**Comment by Notplayingallday383** [comment]
Hi there, Thanks for mentioning this it appears I forgot to update the bare servers for this to use the new server hold on ill fix it

**Comment by Notplayingallday383** [comment]
Issue should have been fixed now let me know if the issue continues to persist
